### ISSUE TITLE
could not get this to work under webpack

### ISSUE THREAD

**Issue by aappddeevv** [DefinitelyScala/scala-js-xmldoc#1]
I was unable to get this to work under webpack. It appears that the global var setting makes it difficult to force the global var to be created under weback under a final bundling into a nodejs application, say, versus the web. I had to add 

```
@js.native
@JSImport("xmldoc", "XmlDocument")
class XmlDocument ...
```
to make it work in node. I was unable to use import-loader or other tricks reliably.

**Comment by KyleU** [comment]
I had no idea folks were making issues for this stuff, sorry for the delay. I'm not really fluent with modern JavaScript, I know Scala.js added bundler support, but these definitions all rely on the global scope. I'll try to get them available as modules too.
